### ISSUE TITLE
MSI-X message control register access

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#3714]
While working to bring up Windows 11 on ARM64 KVM with an iMX8 board, we discover something strange.

Windows' PCI driver writes to the message control register in the MSI-X capability. It is issuing correctly a 2-byte write with offset 2, but Cloud Hypervisor is seeing a 4-byte write with offset 0. The same happens with QEMU too. Looking at KVM's code, it extracts the value directly from ESR_EL2.

QEMU is able to cope with it because it doesn't care about the length and offset of the write. https://github.com/qemu/qemu/blob/ad38520bdeb2b1e0b487db317f29119e94c1c88d/hw/pci/pci.c#L1454

Cloud Hypervisor does not cope because it has stricter requirements. The length and offset must both be 2. https://github.com/cloud-hypervisor/cloud-hypervisor/blob/42b5d4a2f7820469bd538ddd19d7f33eea6f68a8/pci/src/configuration.rs#L738

This does not happen with Linux. Only Windows 11 is able to trigger this issue.

I put in a simple patch to make Windows work. I would like to understand how others would want to make it work.

P.S. Write-1-to-clear doesn't seem to be supported by Cloud Hypervisor either. I don't have a use case for that yet, but if we end up overhauling this part it may be something to consider adding too.

CC @michael2012z @weltling

**Comment by rbradford** [comment]
How is the 2 byte/offset 2 write being turned into a 4-byte write with offset 0? (Something inside KVM?) The PCI spec tells me that two bytes at offset 0 are the read only MSI capability header. What is the contents of the DWORD it's trying to write?

**Comment by liuw** [comment]
> How is the 2 byte/offset 2 write being turned into a 4-byte write with offset 0? (Something inside KVM?) The PCI spec tells me that two bytes at offset 0 are the read only MSI capability header. What is the contents of the DWORD it's trying to write?

I would say something happened inside the hardware, because KVM is not just reading from a register. https://github.com/torvalds/linux/blob/c5d9ae265b105d9a67575fb67bd4650a6fc08e25/arch/arm64/kvm/mmio.c#L155

Generally I think writes to RO bits are going to be discarded -- message control register has RO bits too.

@weltling has the setup. He can tell you the values. I only did the analysis and wrote a simple patch to verify my idea.

**Comment by rbradford** [comment]
You mention hardware. Is this with a virtio device or a VFIO device? I don't think Cloud Hypervisor is correctly ignoring writes to RO fields.

**Comment by liuw** [comment]
"Hardware" means CPU here. ESR_EL2 is a register on ARM64.

The device is a virtio block device.

At least for the message control register, CH only looks at masked and enabled bits and ignore the rest (see set_msg_ctl). I wish writable bits and w1c bits were handled more elegantly.

**Comment by rbradford** [comment]
> "Hardware" means CPU here. ESR_EL2 is a register on ARM64.
> 
> The device is a virtio block device.
> 
> At least for the message control register, CH only looks at masked and enabled bits and ignore the rest (see set_msg_ctl). I wish writable bits and w1c bits were handled more elegantly.

Yes, within that field. But I was actually thinking about something like a 2 byte write to offset 0 would end up going through here:

https://github.com/cloud-hypervisor/cloud-hypervisor/blob/42b5d4a2f7820469bd538ddd19d7f33eea6f68a8/pci/src/configuration.rs#L747-L755

**Comment by michael2012z** [comment]
So, was this issue resolved by https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3715?

**Comment by liuw** [comment]
> So, was this issue resolved by #3715?

No. That is just dealing with writable bits. CH will still see the bogus length and offset.
